##### DEFAULT SHELL #####
set-option -g default-command "${SHELL} -l"

##### MOUSE + VI MODE #####
set -g mouse on
setw -g mode-keys vi

##### PANE NAVIGATION #####
bind-key -n C-o next-windo
bind-key -n C-i resize-pane -Z

bind-key -n C-[ if-shell '[ "$(tmux display -p "#{pane_width}")" -lt "$((`tmux display -p "#{window_width}"` / 2))" ]' \
    'resize-pane -x 50%' \
    'resize-pane -x 30%'


bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

bind -n C-\\ split-window -h

##### STATUS BAR #####

# Hide status bar by default
set -g status on

# Toggle status bar with Ctrl-b
bind -n C-b if -F '#{==:#{status},on}' 'set status off' 'set status on'

##### MISC #####
set -sg escape-time 0
set-option -g allow-rename on
